name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login
      run: |
        docker login -u ugorwx \
        -p ${{ secrets.DOCKER_TOKEN }}

    - name: Build
      run: docker build . -t fsub:${{ github.sha }}

    - name: Tag
      run: docker tag fsub:${{ github.sha }} fsub:latest

    - name: Push
      run: |
        docker push fsub:${{ github.sha }}
        docker push fsub:latest